(kill-new "ldd example_pkg/example.cpython-38-x86_64-linux-gnu.so")
(kill-new "auditwheel repair septembrse-0.0.0-cp38-cp38-linux_x86_64.whl")
(kill-new "auditwheel show septembrse-0.0.0-cp38-cp38-linux_x86_64.whl")
(kill-new "ls -l | grep .whl$")
(kill-new "/opt/python/cp38-cp38/bin/pip wheel .")
(kill-new "apt update && apt install libopenblas-dev")
(kill-new "ls /opt/python")
(kill-new "pip install dist/septembrse-0.0.0-cp39-cp39-linux_x86_64.whl")
(kill-new "unzip -l dist/septembrse-0.0.0-cp39-cp39-linux_x86_64.whl")
(kill-new "ls -l dist/")
(kill-new "python setup.py bdist_wheel")
(kill-new "pip install numpy --no-cache")
