name: Build

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.1

      - name: Install OpenBLAS on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install openblas

      - name: Build wheels on Linux and MacOS
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL_LINUX: "apt update && apt install libopenblas-dev"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
